### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by kiranreddy20** [dend/foggycam#33]
Welcome to FoggyCam 1.0 - Nest video/image capture tool
D:\nestcam\foggycam-master\config.json
Unpickling cookies...
Failed to re-use the cookies. Re-initializing session...
INFO: Initializing session...
INFO: Session initialization complete!
INFO: Performing user login...
INFO: Auth post data
access_token=
b'{"status": 403, "items": [], "status_description": "unauthorized", "status_detail": "Unauthorized."}'
INFO: Initializing current user...
INFO: Requesting user data from:
https://home.nest.com/api/0.1/user//app_launch
Traceback (most recent call last):
  File "start.py", line 16, in <module>
    CAM.start()
  File "D:\nestcam\foggycam-master\src\foggycam.py", line 78, in start
    self.initialize_user()
  File "D:\nestcam\foggycam-master\src\foggycam.py", line 248, in initialize_user
    response = self.merlin.open(request)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

**Comment by kiranreddy20** [comment]
i am using python 3.7

**Comment by dend** [comment]
@kiranreddy20 it looks like it's failing to authenticate you. Have you specified the correct email and password within the configuration file?

**Comment by kratos13** [comment]
Ensure that ::
1) you have added your email and password in the config.json file 
and/or
2) disabled your 2FA
((I have not had luck with the 2FA using the 1.3 version)), but love everything about FoggyCam so far.

**Comment by Angrod** [comment]
having the same auth issues signing in as a migrated account, email and password are correct but can only sign in on web/app using the "sign in with google" option. should this be the case?

**Comment by dend** [comment]
Check the latest change: 8839bc9

I've made some pretty big changes to the application infrastructure, so this should be addressed.
