### ISSUE TITLE
SSL error on Ubuntu 20.04.1

### ISSUE THREAD

**Issue by rarrr** [dend/foggycam#56]
Built with these settings
![image](https://user-images.githubusercontent.com/7687585/104092998-b69d2700-52db-11eb-9de5-edbdc8301761.png)
>[log] Setting up connection to wss://xxxxxxx.dropcam.com:80/nexustalk...
[log] Socket errored out.
Authentication failed, see inner exception.
Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
 ---> Interop+Crypto+OpenSslCryptographicException: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, ReadOnlySpan`1 input, Byte[]& sendBuf, Int32& sendCount)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteSslContext& context, ReadOnlySpan`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
System.Security.Authentication.AuthenticationException
[log] Socket errored out.
You must send data by websocket after websocket is opened!

>System.Exception

**Comment by skydiverMN** [comment]
Unsubscribe

**Comment by dend** [comment]
Thanks @rarrr - will investigate this. I haven't extensively tested the project on Ubuntu just yet, but it's on the radar once I improve the Windows stability.
