### ISSUE TITLE
[error] The capture errored out for the following reason: Unauthorized

### ISSUE THREAD

**Issue by rarrr** [dend/foggycam#68]
After a while I get...
[error] The capture errored out for the following reason: Unauthorized
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at foggycam.Program.ProcessReceivedData(Byte[] buffer) in C:\Users\XXXXXXXXX\foggycam\foggycam\Program.cs:line 402
   at WebSocket4Net.WebSocket.OnDataReceived(Byte[] data, Int32 offset, Int32 length)
   at SuperSocket.ClientEngine.AuthenticatedStreamTcpSession.ReadAsync()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by dend** [comment]
Thanks for the report @rarrr - will be investigating the issue.

**Comment by olie93** [comment]
I am getting the same error:

[error] The capture errored out for the following reason: Unauthorized
[log] Socket errored out.
A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied.

System.Net.Sockets.SocketException
[log] Setting up connection to wss://oculus7215-us1.dropcam.com:80/nexustalk...
[error] The capture errored out for the following reason: Unauthorized
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at foggycam.Program.ProcessReceivedData(Byte[] buffer) in C:\Users\XXXXXX\Downloads\foggycam-experimental\foggycam-experimental\foggycam\Program.cs:line 361
   at foggycam.Program.Ws_DataReceived(Object sender, DataReceivedEventArgs e) in C:\Users\XXXXX\Downloads\foggycam-experimental\foggycam-experimental\foggycam\Program.cs:line 356
   at WebSocket4Net.WebSocket.OnDataReceived(Byte[] data, Int32 offset, Int32 length)
   at SuperSocket.ClientEngine.AuthenticatedStreamTcpSession.ReadAsync()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()


Runs for about an hour before erroring

**Comment by rarrr** [comment]
I gave up on this ever being fixed so changed foggycam to quit on Unauthorized and wrote a python program to monitor it, if it quits, re start it.
