### ISSUE TITLE
Request module error

### ISSUE THREAD

**Issue by kevin-og** [dend/foggycam#7]
Traceback (most recent call last):
  File "start.py", line 6, in <module>
    from foggycam import FoggyCam
  File "/home/kevin/foggycam/src/foggycam.py", line 3, in <module>
    from urllib.request import urlopen
ImportError: No module named request

Does requirements.txt need an update?  I've tried to pip install requests but does not resolve the issue.

**Comment by dend** [comment]
@kevin-og should be a built-in module. Are you building this with Python 3?

**Comment by kevin-og** [comment]
@dend Python 2.  Tried python3 start.py and got farther.  My phone triggers the 2FA, how/when do I enter that? FYI, I'm not using a GUI.

Welcome to FoggyCam 1.0 - Nest video/image capture tool
/home/kevin/foggycam/config.json
INFO: Initializing session...
Traceback (most recent call last):
  File "/home/kevin/foggycam/src/foggycam.py", line 103, in initialize_session
    response = self.merlin.open(request)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "start.py", line 15, in <module>
    CAM = FoggyCam(username=CONFIG.username, password=CONFIG.password)
  File "/home/kevin/foggycam/src/foggycam.py", line 62, in __init__
    self.initialize_session()
  File "/home/kevin/foggycam/src/foggycam.py", line 126, in initialize_session
    unauth_content = json.loads(error_message)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

**Comment by cwwilson08** [comment]
I had to go to python 3.6 to make it work.

**Comment by dend** [comment]
@kevin-og interesting, are you using the correct username/password combination in the config file? Did you modify anything in the source?

@cwwilson08 you can disable the Azure upload in `config.json` by setting `upload_to_azure` to `false`

**Comment by cwwilson08** [comment]
Sorry I was not clear enough. I originally had same error has op. A little googling said there was an issue in Python 3.5 that was corrected in 3.6. Upgrading python and adjusting the commands got the code running for me.

The thing with azure is actually related to issue 2 about 403 request. No version of foggycam has captured an image for me yet when running in azure cloud. It works great in other clouds.

**Comment by kevin-og** [comment]
@dend yes, config has correct credentials, nothing else altered.

**Comment by rahimk** [comment]
Stuck on Azure cloud as well with python3 as starting point. Any help would be appreciated.

`Orion:src Rahim$ python3 start.py
Traceback (most recent call last):
  File "start.py", line 6, in <module>
    from foggycam import FoggyCam
  File "/Users/Rahim/Documents/foggycam-master/src/foggycam.py", line 16, in <module>
    from azurestorageprovider import AzureStorageProvider
  File "/Users/Rahim/Documents/foggycam-master/src/azurestorageprovider.py", line 3, in <module>
    from azure.storage.blob import BlockBlobService, ContentSettings
ImportError: No module named 'azure'`

**Comment by jamiedresser** [comment]
Hi, Same error here. 

Tried using Python 2 (default in High Sierra)
Home-Theatre-Mac-Mini-2:src jdresser$ python start.py
Traceback (most recent call last):
  File "start.py", line 6, in <module>
    from foggycam import FoggyCam
  File "/Users/jdresser/Desktop/foggycam-master/src/foggycam.py", line 3, in <module>
    from urllib.request import urlopen
ImportError: No module named request
Home-Theatre-Mac-Mini-2:src jdresser$ 

And then tried using Python 3.

Home-Theatre-Mac-Mini-2:src jdresser$ python3 start.py
Traceback (most recent call last):
  File "start.py", line 6, in <module>
    from foggycam import FoggyCam
  File "/Users/jdresser/Desktop/foggycam-master/src/foggycam.py", line 17, in <module>
    from azurestorageprovider import AzureStorageProvider
  File "/Users/jdresser/Desktop/foggycam-master/src/azurestorageprovider.py", line 3, in <module>
    from azure.storage.blob import BlockBlobService, ContentSettings
ModuleNotFoundError: No module named 'azure'
Home-Theatre-Mac-Mini-2:src jdresser$ 

Thanks for writing this - hope to get it working!! :)

**Comment by theCheek** [comment]
I too have just stumbled across this project, got excited, but have also encountered the same error as @kevin-og and @rahimk  

Did you guys ever get this working?

`Traceback (most recent call last):
  File "start.py", line 15, in <module>
    CAM = FoggyCam(username=CONFIG.username, password=CONFIG.password)
  File "/volume1/Applications/foggycam/src/foggycam.py", line 73, in __init__
    self.initialize_session()
  File "/volume1/Applications/foggycam/src/foggycam.py", line 138, in initialize_session
    session_json = json.loads(session_data)
  File "/volume1/@appstore/python3/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
`

**Comment by ExpertSkinDoc** [comment]
I initially encountered the same problem as **@jamiedresser**:

iMac2:src Expert$ python3 start.py
Traceback (most recent call last):
  File "start.py", line 6, in <module>
    from foggycam import FoggyCam
  File "/Users/Expert/Downloads/foggycam-master/src/foggycam.py", line 17, in <module>
    from azurestorageprovider import AzureStorageProvider
  File "/Users/Expert/Downloads/foggycam-master/src/azurestorageprovider.py", line 3, in <module>
    from azure.storage.blob import BlockBlobService, ContentSettings
ModuleNotFoundError: No module named 'azure' 

I commented out line 17 in foggycam.py: """from azurestorageprovider import AzureStorageProvider"""

I then get

iMac2:src Expert$ python3 start.py
Welcome to FoggyCam 1.0 - Nest video/image capture tool
/Users/Expert/Downloads/foggycam-master/config.json
Traceback (most recent call last):
  File "start.py", line 13, in <module>
    CONFIG = json.load(open(CONFIG_PATH), object_hook=lambda d: namedtuple('X', d.keys())(*d.values()))
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd2 in position 37: invalid continuation byte

What I am doing wrong? I tried reinstalling 'azure', no help. What is this 

>File "/Users/Expert/Downloads/foggycam-master/src/azurestorageprovider.py", line 3, in `<`module`>`
>` `   from azure.storage.blob import BlockBlobService, ContentSettings 
>ModuleNotFoundError: No module named 'azure'

Running macOS High Sierra Version 10.13.6 iMac (Retina 5K, 27-inch, Late 2015)

**Comment by dend** [comment]
Have you folks installed the requirements (`pip install -r requirements.txt`)?

**Comment by Game2Freak** [comment]
hello,

I seem to be having the same issue as others:
`Traceback (most recent call last):
  File "start.py", line 6, in <module>
    from foggycam import FoggyCam
  File "/root/foggycam/src/foggycam.py", line 3, in <module>
    from urllib.request import urlopen
ImportError: No module named request
`
I have all the requirements installed.

Any help with this issue would be appreciated.

**Comment by rajnagar92** [comment]
Same problems here. I have satisfied the requirements in requirements.txt

In python2 I get a “no module named request” error and in python3 I get a “no module named azure” error. 

Tired commenting out a million things and then got to a “no module named http.cookiejar” error.

**Comment by jedis00** [comment]
Had this same issue. Resolved by installing Python 3 and reinstalling the requirements for Python 3.

If you have Python 2 and 3 installed, whichever was installed first (likely v2), is where 'pip' will point. Use the second command to tell it to install the Python 3 dependencies.

On Amazon Linux:
`sudo yum install python36 -y
sudo python3 -m pip install -r requirements.txt`

**Comment by dend** [comment]
Check the latest change: 8839bc9

Because the application is no longer Python-based, this is not quite applicable :)
