### ISSUE TITLE
Error when trying to run requirements.txt

### ISSUE THREAD

**Issue by chest069** [dend/foggycam#79]
Hey,

I just found this and love the fact it works with the nest cam. I am trying to follow the instructions in the read me where it says

`## How To Start

Make sure you install the requirements for the project, by `cd`-ing in the folder with the project, and running:

```
pip install -r requirements.txt
````
I get the following error when I try and run it:

`C:\Users\chest\Downloads\foggycam-1.3\foggycam-1.3\src>pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Collecting azure-storage-blob==0.37.1
  Using cached azure_storage_blob-0.37.1-py2.py3-none-any.whl (77 kB)
Collecting python-dateutil
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 kB 3.8 MB/s eta 0:00:00
Collecting cryptography
  Downloading cryptography-37.0.4-cp36-abi3-win_amd64.whl (2.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 6.4 MB/s eta 0:00:00
Collecting futures
  Using cached futures-3.0.5.tar.gz (25 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "C:\Program Files\Python310\lib\site-packages\setuptools\__init__.py", line 189, in <module>
          monkey.patch_all()
        File "C:\Program Files\Python310\lib\site-packages\setuptools\monkey.py", line 99, in patch_all
          patch_for_msvc_specialized_compiler()
        File "C:\Program Files\Python310\lib\site-packages\setuptools\monkey.py", line 169, in patch_for_msvc_specialized_compiler
          patch_func(*msvc14('_get_vc_env'))
        File "C:\Program Files\Python310\lib\site-packages\setuptools\monkey.py", line 149, in patch_params
          mod = import_module(mod_name)
        File "C:\Program Files\Python310\lib\importlib\__init__.py", line 126, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "C:\Program Files\Python310\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 20, in <module>
          import unittest.mock
        File "C:\Program Files\Python310\lib\unittest\mock.py", line 26, in <module>
          import asyncio
        File "C:\Program Files\Python310\lib\asyncio\__init__.py", line 8, in <module>
          from .base_events import *
        File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 18, in <module>
          import concurrent.futures
        File "C:\Users\chest\AppData\Local\Temp\pip-install-5la2o6st\futures_4ec7f1a709b2464da90853ba065dbc6a\concurrent\futures\__init__.py", line 8, in <module>
          from concurrent.futures._base import (FIRST_COMPLETED,
        File "C:\Users\chest\AppData\Local\Temp\pip-install-5la2o6st\futures_4ec7f1a709b2464da90853ba065dbc6a\concurrent\futures\_base.py", line 357
          raise type(self._exception), self._exception, self._traceback
                                     ^
      SyntaxError: invalid syntax
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

Can someone help me out I would like to get this going. Also does anyone know if there is something like this available for UNRAID so I could install it there?

Thanks for any help on this because I am not sure what to do at this point.

**Comment by chest069** [comment]
Oh, I am running this on a Windows 11 64bit machine.
